### ISSUE TITLE
Load AWS Availability Zones for Consul configuration

### ISSUE THREAD

**Issue by ghost** [spring-cloud/spring-cloud-aws#253]
At Amazon AWS, all calls inside the same Availability Zone (AZ) has no cost, but there is a cost for calls between services hosted in diferent AZ.

We want to configure Consul with the current AZ, so it's detected automatically, and Ribbon priorizes the same zone server.

At [spring-cloud-consul](http://cloud.spring.io/spring-cloud-consul/spring-cloud-consul.html): _Spring Cloud Consul uses Consul tags to approximate metadata until Consul officially supports metadata._

So you can configure the zone statically:

```
    spring:
      cloud:
        consul:
          discovery:
            tags: zone=myZone
```

The zone is loaded:

```
    {
        "serviceId": "testConsulApp-8080",
        "host": "...",
        "port": 8080,
        "secure": false,
        "metadata": {
            "zone": "myZone"
        },
        "uri": "..."
    }
```

At [spring-cloud-aws](http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html): _The instance metadata is automatically available in a Spring Boot application as a property source if the application is running on an EC2 instance. Instance metadata can be used in XML, Java placeholders and expressions._

Configuring consul with the `placement/availability-zone` placeholder:

```
    spring:
      cloud:
        consul:
          discovery:
            tags: zone=${placement/availability-zone:UndefinedZone}
```

The zone it's not loaded:

```
		"test-8080": {
			"id": "test-8080",
			"service": "test",
			"tags": [
				"zone=UndefinedZone"
			],
			"address": "...",
			"port": 8080
		},
```

Any suggestion ?

Thanks !
