### ISSUE TITLE
Allow adding any arbitrary AWS Secrets Manager secrets 

### ISSUE THREAD

**Issue by tvrmsmith** [spring-cloud/spring-cloud-aws#515]
It would be great if we could add additional AWS Secrets Manager secrets as property sources. Currently, I'd like to use the RDS secrets feature as well as other secrets, but the current way of adding secrets makes it difficult to do this.

It could be configured something like:
```
aws:
  secretsmanager:
    additional-secrets:
      - /secret/secret1
      - /secret/secret2
```

**Comment by maciejwalkowiak** [comment]
@tvrmsmith just so that I understand it correctly - these additional secrets would contains raw values and everything after prefix (`/secret/`) would he a property name?

**Comment by eddumelendez** [comment]
I think [this link](https://aws.amazon.com/blogs/security/rotate-amazon-rds-database-credentials-automatically-with-aws-secrets-manager/) can be useful to understand the proposal. @tvrmsmith is what you meant?

**Comment by maciejwalkowiak** [comment]
In case of RDS password I would like us to use this library in 3.0 https://github.com/aws/aws-secretsmanager-jdbc. I have it working in the prototype (... and made video about it how to use this library ;-) https://www.youtube.com/watch?v=gIbr6-AR6T8)

**Comment by nhomble** [comment]
Instead of an array of strings, maybe we should be a little more flexible and allow users to configure the desired name as well? I think we're going to hit a wall if we only depend on the library to interpret the secret name from the path. Maybe like

```yml
aws:
  secretsmanager:
    additional-secrets:
      secret1:
        path: /secret/secret1
      different-name:
        path: /secret/secret2
```
